### ISSUE TITLE
Migrate Database to AWS

### ISSUE THREAD

**Issue by ryanjhkim** [ryanjhkim/bagel#8]
create a new account with free tier
look at dynamodb alternatives
create a db
update the code to use the db
test locally

**Comment by gokcedilek** [comment]
1. Continue to use DynamoDB
2. Consider putting a maximum on the number of workers that client can request
3. Need to store Hash(?) - depends on hashing algo, if it returns the same one.
4. Create a new column/table(???) that labels ea. vertex to the worker it belongs to based on the number of total workers of the query; A new column will be created ea time for a new number of workers; else we will use the previously stored column
    - (Future Consideration) LRU cache on # of columns cached (workers) OR cap on the number of workers client can use. OR both :)

**Comment by gokcedilek** [comment]
1. Research local dynamoDB setup and write documentation
2. Resize web-Google graph to smaller.
